"""empty message

Revision ID: 6262d0984b6a
Revises: 
Create Date: 2025-02-19 18:01:16.601726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6262d0984b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=400), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('poblacion', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('fecha_obtencion_carnet', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('potencia', sa.String(length=10), nullable=False),
    sa.Column('plazas', sa.Integer(), nullable=False),
    sa.Column('combustible', sa.String(length=20), nullable=False),
    sa.Column('autonomia', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=300), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('precio_por_dia', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('vehiculo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
