"""empty message

Revision ID: 988b3a3f039a
Revises: b50950722883
Create Date: 2025-02-11 15:58:08.595407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988b3a3f039a'
down_revision = 'b50950722883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('apellidos',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('contraseña',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
